name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on:- task: AzureAppServiceSettings@1
  inputs:
    azureSubscription: 'Pay-As-You-Go (fed31085-2f87-41a5-813d-66cb81658a99)'
    appName: 'bradyblazorweather'
    resourceGroupName: 'BradyBlazorWeather'

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal