# ASP.NET Core
azure-pipelines-DevOps-interview
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'BradyWeather.Blazor.Server.csproj'
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.1'
main
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:

- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
